[phases.setup]
nixPkgs = ["nodejs_20"]

[phases.install]
cmds = [
  "npm install",
  "npm install --prefix client",
  "npm install --prefix server"
]

[phases.build]
cmds = ["npm run build --prefix client"]

[start]
cmd = "node server/src/index.js"
